[package]
name = "gsim-client"
version.workspace = true
edition.workspace = true

[dependencies]
gsim-core.workspace = true
gsim-proto.workspace = true
gsim-server.workspace = true
gsim-client-core.workspace = true
gsim-swarm.workspace = true
rayon.workspace = true
clap.workspace = true
macroquad = { version = "0.4", default-features = false }
egui-macroquad = { version = "0.17", default-features = false }
ureq = "2"
self-replace = "1"

[target.'cfg(target_os = "macos")'.dependencies]
flate2 = "1"
tar = "0.4"

[[bin]]
name = "gsim-client"
path = "src/main.rs"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
